version: '3.4'

networks:
  pcstore:

services:
  sqlserverdb:
    container_name: sqlserverdb
    image: ${DOCKER_REGISTRY-}mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8003:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - pcstore

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 18005:27017
    networks:
      - pcstore

  usermanager.api:
    container_name: user-manager-api
    image: ${DOCKER_REGISTRY-}usermanagerapi
    build:
      context: .
      dockerfile: UserManager.API/Dockerfile
    networks:
      - pcstore
    environment:
      - DB_HOST=mongodb
      - DB_NAME=PCStoreUserManager

  pcstore.api:
    container_name: pc-store-api
    image: ${DOCKER_REGISTRY-}pcstoreapi
    build:
      context: .
      dockerfile: PCStore.API/Dockerfile
    depends_on:
      - sqlserverdb
    environment:
      - DB_HOST=sqlserverdb
      - DB_NAME=PCStoreMicroservices
      - DB_SA_PASSWORD=password@12345#
    networks:
      - pcstore

  rabbitmq:
    container_name: rabbitmq
    image: ${DOCKER_REGISTRY-}rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    networks:
      - pcstore

  ocelot.api:
    container_name: ocelot.api
    image: ${DOCKER_REGISTRY-}ocelotapi
    build:
      context: .
      dockerfile: Ocelot.API/Dockerfile
    networks:
      - pcstore
    ports:
      - 8001:80
